spring.profiles.active=dev
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring.application.name=report-btp
springdoc.swagger-ui.path=/swagger-ui.html
spring.main.allow-bean-definition-overriding=true
module-name=bttp-service
api-version=v1
spring.main.allow-circular-references=true
#spring.jpa.show-sql=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
application.storage.bucket=${STORAGE_BUCKET:/home/bttp_files/}