server.port=3976

#####################
# JackSon Configuration
#####################

### First Oracle Database (DB1 bộ tư pháp - công chứng)
spring.datasource.db1.jdbcUrl=jdbc:oracle:thin:@192.168.1.88:1521/VNPTKST
spring.datasource.db1.username=tcccadmin
spring.datasource.db1.password=tccc89##2019
spring.datasource.db1.driver-class-name=oracle.jdbc.OracleDriver

### Second Oracle Database (DB2 đấu giá )
spring.datasource.db2.jdbcUrl=jdbc:oracle:thin:@192.168.1.88:1521/VNPTKST
spring.datasource.db2.username=btp_dgts
spring.datasource.db2.password=dgts2019##
spring.datasource.db2.driver-class-name=oracle.jdbc.OracleDriver

### Second Oracle Database (DB3 tài khoản )
spring.datasource.jdbcUrl=jdbc:oracle:thin:@192.168.1.162:1521/orcl
spring.datasource.username=bttp
spring.datasource.password=Bt56$%##TP24$
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

### Second Oracle Database (DB3 tài khoản )
spring.datasource.db4.jdbcUrl=jdbc:oracle:thin:@192.168.1.162:1521/orcl
spring.datasource.db4.username=btp_law_practice
spring.datasource.db4.password=lawpractice2025@@#$
spring.datasource.db4.driver-class-name=oracle.jdbc.OracleDriver

#####################
# JackSon Configuration
#####################
spring.properties.jackson.serialization.write-dates-as-timestamps=true
spring.properties.jackson.time-zone=Asia/Ho_Chi_Minh




#####################
# Mail Configuration
#####################
mail.account=Report BTP Application
mail.sender.username=chonso.noreply@ospgroup.vn
mail.sender.password=Tdt@1668
mail.sender.alias=Rport BTP Online
mail.host=smtp.yandex.com
mail.port=465
mail.provider=yandex
mail.debug=true
mail.to=thangdt@gmail.com

#####################
# JWT Configuration
#####################
jwt.secret=GqxqMUz7x3Ffy_IDBW6A001gR4EF_JEV9VwrXP3GDXK9aW-j
jwt.expires_in=7776000000


#####################
# Redis Configuration
#####################
spring.data.redis.database=0
spring.data.cache.type=redis
spring.data.redis.host=192.168.1.52
spring.data.redis.port=6379
spring.data.redis.timeout=60000
redis.enable=true