package com.osp.bttp;

import com.osp.bttp.common.security.TokenHelper;

// Generated by Qodo Gen

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import org.junit.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.util.ReflectionTestUtils;

import javax.crypto.SecretKey;
import java.util.HashMap;
import java.util.Map;

import static org.junit.Assert.*;

@SpringBootTest
public class GeneratetokenTest {


    // Generates a valid JWT token with correct claims
    @Test
    public void test_generate_token_with_valid_username_and_claims() {
        TokenHelper tokenHelper = new TokenHelper();
        ReflectionTestUtils.setField(tokenHelper, "APP_NAME", "bttp");
        ReflectionTestUtils.setField(tokenHelper, "SECRET", "GqxqMUz7x3Ffy_IDBW6A001gR4EF_JEV9VwrXP3GDXK9aW-j");
        ReflectionTestUtils.setField(tokenHelper, "EXPIRES_IN", 77760000000L); // 15 năm
        String username = "base_auth";
        /*
        eyJhbGciOiJIUzUxMiJ9.eyJ1c2VybmFtZSI6ImJhc2VfYXV0aCIsImlzcyI6ImJ0dHAiLCJzdWIiOiJiYXNlX2F1dGgiLCJpYXQiOjE3Mjg2MzA0MDcsImV4cCI6OTUwNDYzMDQwN30.ynwYWu7UxxL2R9J0pqh3F5j5t5tIE-RJNbyBuMBi_HQVMYNQnW3dgLOhlFgyjx8JR4EWoOT8ME-t03wX2-PafQ
         */
        Map<String, Object> mapClaims = new HashMap<>();
        String token = tokenHelper.generateToken(username, mapClaims);
        assertNotNull(token);
//        Claims parsedClaims = Jwts.parser().setSigningKey("bttp_fasokwm2k1").build().parseClaimsJws(token).getBody();
        Claims parsedClaims = Jwts.parser()
                .verifyWith((SecretKey) tokenHelper.key("GqxqMUz7x3Ffy_IDBW6A001gR4EF_JEV9VwrXP3GDXK9aW-j"))
                .build()
                .parseSignedClaims(token)
                .getPayload();
        assertEquals(username, parsedClaims.getSubject());
        assertEquals("base_auth", parsedClaims.get("username"));
    }
}